export const LETTER_PAIR_TO_WORD = {
    // list of all letter pairs starting with letter A and having a blank value
    "AA": "",
    "AB": "abab",
    "AC": "acac",
    "AD": "adad",
    "AE": "aeae",
    "AF": "af",
    "AG": "agag",
    "AH": "ahah",
    "AI": "aji",
    "AJ": "aja",
    "AK": "aka",
    "AL": "alal",
    "AM": "amu",
    "AN": "annie",
    "AO": "ao",
    "AP": "apep",
    "AQ": "aku",
    "AR": "arr",
    "AS": "as",
    "AT": "ata",
    "AU": "ału",
    "AW": "awu",
    "AZ": "azet",
    // list of all letter pairs starting with letter B and having a blank value
    "BA": "",
    "BB": "",
    "BC": "",
    "BD": "",
    "BE": "",
    "BF": "",
    "BG": "",
    "BH": "",
    "BI": "",
    "BJ": "",
    "BK": "",
    "BL": "",
    "BM": "",
    "BN": "",
    "BO": "",
    "BP": "",
    "BQ": "",
    "BR": "",
    "BS": "",
    "BT": "",
    "BU": "",
    "BW": "",
    "BZ": "",
    // list of all letter pairs starting with letter C and having a blank value


};